### ISSUE TITLE
we are trying to use your approach, but sadly it keeps failing with...

### ISSUE THREAD

**Issue by berlinguyinca** [gustavoguimaraes/my-ico#2]
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/lib/node_modules/truffle/build/cli.bundled.js:222830:46)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:35149:25
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:224768:9
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:66971:11
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:67535:24)

Do you have any idea how to solve this issue?

kind regards,

Gert

**Comment by siukwai** [comment]
@berlinguyinca I'm having the same problem trying to deploy to testnet. Failing on migration step 2; first contract deploys no problem. What did you do to fix the problem?

**Comment by lexruster** [comment]
the same for second contract
Error: The contract code couldn't be stored, please check your gas amount.

**Comment by ranjancse26** [comment]
@berlinguyinca Please increase the gas limit, that should fix the problem
